# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='matches.proto',
  package='sfm',
  serialized_pb='\n\rmatches.proto\x12\x03sfm\"P\n\x08\x44Matches\x12\x10\n\x08queryIdx\x18\x01 \x01(\r\x12\x10\n\x08trainIdx\x18\x02 \x01(\r\x12\x0e\n\x06imgIdx\x18\x03 \x01(\r\x12\x10\n\x08\x64istance\x18\x04 \x01(\x02\"T\n\x0cMatchesProto\x12\x11\n\timageLseq\x18\x01 \x01(\x06\x12\x11\n\timageRseq\x18\x02 \x01(\x06\x12\x1e\n\x07matches\x18\x03 \x03(\x0b\x32\r.sfm.DMatchesB)\n\x14\x63vg.sfmPipeline.mainB\x11MatchesOutMessage')




_DMATCHES = descriptor.Descriptor(
  name='DMatches',
  full_name='sfm.DMatches',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='queryIdx', full_name='sfm.DMatches.queryIdx', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='trainIdx', full_name='sfm.DMatches.trainIdx', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='imgIdx', full_name='sfm.DMatches.imgIdx', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='distance', full_name='sfm.DMatches.distance', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=102,
)


_MATCHESPROTO = descriptor.Descriptor(
  name='MatchesProto',
  full_name='sfm.MatchesProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='imageLseq', full_name='sfm.MatchesProto.imageLseq', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='imageRseq', full_name='sfm.MatchesProto.imageRseq', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='matches', full_name='sfm.MatchesProto.matches', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=188,
)

_MATCHESPROTO.fields_by_name['matches'].message_type = _DMATCHES
DESCRIPTOR.message_types_by_name['DMatches'] = _DMATCHES
DESCRIPTOR.message_types_by_name['MatchesProto'] = _MATCHESPROTO

class DMatches(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DMATCHES
  
  # @@protoc_insertion_point(class_scope:sfm.DMatches)

class MatchesProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MATCHESPROTO
  
  # @@protoc_insertion_point(class_scope:sfm.MatchesProto)

# @@protoc_insertion_point(module_scope)
