# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import data_pb2
import matches_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='unionProto.proto',
  package='sfm',
  serialized_pb='\n\x10unionProto.proto\x12\x03sfm\x1a\ndata.proto\x1a\rmatches.proto\"Q\n\x0bSFMpipeline\x12\x1e\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x0f.sfm.FrameProto\x12\"\n\x07matches\x18\x02 \x01(\x0b\x32\x11.sfm.MatchesProto')




_SFMPIPELINE = descriptor.Descriptor(
  name='SFMpipeline',
  full_name='sfm.SFMpipeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='frame', full_name='sfm.SFMpipeline.frame', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='matches', full_name='sfm.SFMpipeline.matches', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=133,
)

_SFMPIPELINE.fields_by_name['frame'].message_type = data_pb2._FRAMEPROTO
_SFMPIPELINE.fields_by_name['matches'].message_type = matches_pb2._MATCHESPROTO
DESCRIPTOR.message_types_by_name['SFMpipeline'] = _SFMPIPELINE

class SFMpipeline(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SFMPIPELINE
  
  # @@protoc_insertion_point(class_scope:sfm.SFMpipeline)

# @@protoc_insertion_point(module_scope)
